import { Organization, Teacher, Student, HomeworkTopic, ClassSession, UserProfile, CourseItem } from '../types';

export const initialOrganizations: Organization[] = [
  {
    id: 'org-arabic-academy',
    name: 'ArabiyatLearn — Arabic Made Simple for Kids',
    domain: 'arabiyatlearn.com',
    logoUrl: '/arabiyat-logo.png',
    primaryColor: '#0C3E35',
    accentColor: '#C8707E',
    activeMonth: '2026-09',
    managerName: 'Academy Director',
    managerEmail: 'admin@arabiyatlearn.com',
    plan: 'academy',
    subscriptionStatus: 'active',
    maxTeachers: 999,
    maxStudents: 9999,
    createdAt: '2026-09-01',
  }
];

export const initialProfiles: UserProfile[] = [
  {
    id: 'usr-director',
    orgId: 'org-arabic-academy',
    role: 'admin',
    name: 'Academy Director',
    email: 'admin@arabiyatlearn.com',
    password: 'admin123',
    phone: '',
  }
];

export const initialTeachers: Teacher[] = [];

export const initialStudents: Student[] = [];

export const initialHomeworkTopics: HomeworkTopic[] = [
  { id: 'top-1', orgId: 'org-arabic-academy', title: 'Fruits', isCustom: false },
  { id: 'top-2', orgId: 'org-arabic-academy', title: 'Numbers', isCustom: false },
  { id: 'top-3', orgId: 'org-arabic-academy', title: 'Shapes', isCustom: false },
  { id: 'top-4', orgId: 'org-arabic-academy', title: 'Colors', isCustom: false },
  { id: 'top-5', orgId: 'org-arabic-academy', title: 'Alphabet', isCustom: false },
  { id: 'top-6', orgId: 'org-arabic-academy', title: 'Animals', isCustom: false },
  { id: 'top-7', orgId: 'org-arabic-academy', title: 'Family', isCustom: false },
  { id: 'top-8', orgId: 'org-arabic-academy', title: 'Greetings', isCustom: false },
  { id: 'top-9', orgId: 'org-arabic-academy', title: 'Vocabulary', isCustom: false },
  { id: 'top-10', orgId: 'org-arabic-academy', title: 'Speaking', isCustom: false },
  { id: 'top-11', orgId: 'org-arabic-academy', title: 'Reading', isCustom: false },
  { id: 'top-12', orgId: 'org-arabic-academy', title: 'Revision', isCustom: false },
];

export const initialCourses: CourseItem[] = [
  {
    id: 'course-1',
    orgId: 'org-arabic-academy',
    slug: 'arabic-alphabet-phonics',
    title: 'Arabic Alphabet & Phonics Playground',
    description: 'An interactive journey through the 28 Arabic letters with fun phonetic games, shape recognition, and foundational sounds.',
    level: 'Beginner',
    category: 'Alphabet',
    price: 49,
    lessonsCount: 16,
    duration: '8 weeks',
    thumbnailUrl: '/assets/course-thumb-1.jpg',
    outcomes: ['Recognize all 28 letters', 'Letter forms (isolated, start, middle, end)', 'Short vowels (Fatha, Kasra, Damma)'],
    status: 'Published',
  },
  {
    id: 'course-2',
    orgId: 'org-arabic-academy',
    slug: 'conversational-arabic-kids',
    title: 'Daily Conversational Arabic for Children',
    description: 'Practical daily vocabulary and dialogues designed for English-speaking kids to speak naturally with family and friends.',
    level: 'Beginner',
    category: 'Speaking',
    price: 69,
    lessonsCount: 24,
    duration: '12 weeks',
    thumbnailUrl: '/assets/course-thumb-2.jpg',
    outcomes: ['Daily greetings and polite expressions', 'Numbers 1-100 and colors', 'Family members and everyday objects'],
    status: 'Published',
  },
  {
    id: 'course-3',
    orgId: 'org-arabic-academy',
    slug: 'quranic-arabic-basics',
    title: "Qur'anic Arabic Basics & Reading Fluency",
    description: "Connect with the language of the Holy Qur'an through step-by-step Tajweed pronunciation rules and high-frequency vocabulary.",
    level: 'Intermediate',
    category: 'Quran',
    price: 79,
    lessonsCount: 20,
    duration: '10 weeks',
    thumbnailUrl: '/assets/course-thumb-3.jpg',
    outcomes: ['Proper Makharij articulation', 'Reading short Surahs with confidence', "Understanding foundational Qur'anic words"],
    status: 'Published',
  },
  {
    id: 'course-4',
    orgId: 'org-arabic-academy',
    slug: 'noorani-qaida-complete',
    title: 'Noorani Qaida — Complete Foundation Course',
    description: 'The complete Noorani Qaida curriculum taught step by step. Perfect for absolute beginners who want to start reading the Quran from scratch with correct pronunciation.',
    level: 'Beginner',
    category: 'Qaida',
    price: 59,
    lessonsCount: 20,
    duration: '10 weeks',
    thumbnailUrl: '/assets/course-thumb-4.jpg',
    outcomes: [
      'All Arabic letters with correct Makharij',
      'Joining letters to form words',
      'Short and long vowels (harakat)',
      'Tanween, Shaddah and Sukoon rules',
      'Reading simple Quranic words confidently',
    ],
    status: 'Published',
  },
  {
    id: 'course-5',
    orgId: 'org-arabic-academy',
    slug: 'tajweed-rules-beginners',
    title: 'Tajweed Rules for Young Readers',
    description: 'Learn the essential Tajweed rules that make Quran recitation beautiful and correct. Taught in simple English with practical examples from the Quran.',
    level: 'Intermediate',
    category: 'Tajweed',
    price: 79,
    lessonsCount: 18,
    duration: '9 weeks',
    thumbnailUrl: '/assets/course-thumb-5.jpg',
    outcomes: [
      'Rules of Noon Sakinah & Tanween',
      'Rules of Meem Sakinah',
      'Madd (elongation) rules',
      'Qalqalah letters',
      'Laam Shamsiyyah & Qamariyyah',
      'Applying rules while reciting Juz Amma',
    ],
    status: 'Published',
  },
  {
    id: 'course-6',
    orgId: 'org-arabic-academy',
    slug: 'quran-memorisation-juz-amma',
    title: "Quran Memorisation — Juz 'Amma (30th Para)",
    description: "Memorise the short Surahs of the 30th Juz with correct Tajweed and understanding of meaning. Ideal for children aged 6-14 who have completed basic reading.",
    level: 'Intermediate',
    category: 'Quran',
    price: 89,
    lessonsCount: 30,
    duration: '15 weeks',
    thumbnailUrl: '/assets/course-thumb-6.jpg',
    outcomes: [
      'Memorise Surahs from Al-Nas to An-Naba',
      'Correct Tajweed application throughout',
      'Basic understanding of Surah meanings',
      'Confident recitation in Salah',
      'Revision techniques for long-term retention',
    ],
    status: 'Published',
  },
  {
    id: 'course-7',
    orgId: 'org-arabic-academy',
    slug: 'daily-duas-islamic-supplications',
    title: 'Daily Duas & Islamic Supplications for Children',
    description: 'Teach your child the essential daily duas with correct pronunciation and meaning. Covers duas for waking up, eating, sleeping, entering the home, and more.',
    level: 'Beginner',
    category: 'Islamic Studies',
    price: 39,
    lessonsCount: 12,
    duration: '6 weeks',
    thumbnailUrl: '/assets/course-thumb-1.jpg',
    outcomes: [
      '30+ essential daily duas memorised',
      'Correct Arabic pronunciation of each dua',
      'English meanings understood',
      'When and how to use each dua',
      'Duas for salah, wudu, and everyday moments',
    ],
    status: 'Published',
  },
  {
    id: 'course-8',
    orgId: 'org-arabic-academy',
    slug: 'quran-reading-fluency-advanced',
    title: "Quran Reading Fluency — Advanced Recitation",
    description: 'For students who can already read Arabic and want to improve speed, fluency and Tajweed application to recite the Quran beautifully and confidently.',
    level: 'Advanced',
    category: 'Quran',
    price: 99,
    lessonsCount: 24,
    duration: '12 weeks',
    thumbnailUrl: '/assets/course-thumb-2.jpg',
    outcomes: [
      'Fluent Quran recitation with Tajweed',
      'Advanced Madd and Waqf rules',
      'Recitation of Juz Amma from memory',
      'Introduction to Juz Tabarak',
      'Preparation for Ijazah pathway',
    ],
    status: 'Published',
  },
  {
    id: 'course-9',
    orgId: 'org-arabic-academy',
    slug: 'arabic-reading-writing-kids',
    title: 'Arabic Reading & Writing for Kids',
    description: 'A structured course teaching children to read and write Arabic script confidently. From letter formation to joining words, taught in an encouraging and fun environment.',
    level: 'Beginner',
    category: 'Alphabet',
    price: 55,
    lessonsCount: 18,
    duration: '9 weeks',
    thumbnailUrl: '/assets/course-thumb-3.jpg',
    outcomes: [
      'Write all 28 Arabic letters correctly',
      'Connect letters to form words',
      'Read simple Arabic text',
      'Letter formation and pen control',
      'Short reading comprehension exercises',
    ],
    status: 'Published',
  },
  {
    id: 'course-10',
    orgId: 'org-arabic-academy',
    slug: 'islamic-studies-children',
    title: 'Islamic Studies for Young Muslims',
    description: 'An age-appropriate Islamic studies programme covering pillars of Islam, pillars of Iman, Islamic history, and how to be a good Muslim in everyday life.',
    level: 'Beginner',
    category: 'Islamic Studies',
    price: 45,
    lessonsCount: 16,
    duration: '8 weeks',
    thumbnailUrl: '/assets/course-thumb-4.jpg',
    outcomes: [
      'Five Pillars of Islam',
      'Six Pillars of Iman',
      'Prophet Muhammad ﷺ — life and character',
      'Islamic manners and character building',
      'Basic Fiqh — wudu, salah, and cleanliness',
    ],
    status: 'Published',
  },
];

export function generateSeptember2026Classes(): ClassSession[] {
  return [];
}
